apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization

namespace: dev
namePrefix: dev-

resource:
- ../../base

components:
  - ../../variants/non-prod

patchesStrategicMerge:
- deployment.yml
- version.yml
- settings.yml